name: Create tag and release

on:
  workflow_dispatch:
    inputs:
      level:
        description: "type of update to perform (patch, minor, major)"
        required: true
        options:
          - patch
          - minor
          - major
        default: patch
        type: choice

permissions:
  packages: write
  actions: write
  id-token: write
  contents: write

jobs:
  build:
    if: github.ref == 'refs/heads/main' # running for "main" only
    name: "build docker image"
    uses: janeapp/ghw-build-and-push-eks/.github/workflows/workflow.yaml@v1
    secrets: inherit
    with:
      environment: EKS-Dev
      level: ${{ inputs.level }}
      use_branch: false

  push-to-staging: # this has unstable and staging argos
    name: "push image to staging ECR"
    runs-on: ubuntu-latest
    needs: build
    environment: EKS-Dev
    steps:
      - name: push to staging
        uses: janeapp/gha-push-image@v0
        with:
          image_tag: ${{ needs.build.outputs.tag }}
          gh_actor: ${{ github.actor }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          aws_role: ${{ vars.AWS_ROLE }}
          aws_region: ${{ vars.AWS_REGION }}
          aws_registry: ${{ vars.REGISTRY }}

  staging-deploy-pr:
    name: "pr to deploy to STAGING"
    runs-on: ubuntu-latest
    needs: [push-to-staging, build]

    steps:
      - name: echo tag
        run: echo ${{ needs.build.outputs.tag }}
      - name: open config PR
        uses: janeapp/gha-open-config-pull-request@v0
        with:
          environment: staging
          image-tag: ${{ needs.build.outputs.tag }}
          app-id: ${{ vars.AUTOMATION_UPDATER_APP_ID }}
          app-private-key: ${{ secrets.AUTOMATION_UPDATER_APP_PRIVATE_KEY }}
          config-repo: ${{ vars.CONFIG_REPO }}
